# src/main/resources/application.yml
server:
  port: 8080

spring:
  datasource:
    # ???? MySQL ???????? blog ??????
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 925115
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update           # ??????/????????????? none / validate?
    show-sql: false

  mail:
    host: smtp.qq.com
    port: 465
    username: 2945706262@qq.com
    password: yplgrzlnexubddad
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 925115

  mvc:
    static-path-pattern: /**
    # Add this to ignore the error
    web:
      resources:
        add-mappings: true

  servlet:
    multipart:
      max-file-size: 5MB        # SMMS limit is 5MB
      max-request-size: 5MB

smms:
  token: 4EWY08X8DEAXz2VHI3uc6O5nr5h6eSJF  # 🔴 Replace this!
  default-avatar: https://s2.loli.net/2026/01/08/Gv8fl7FQ9kS4ON1.jpg # 🔴 Replace with your uploaded default image URL

minio:
  endpoint: http://127.0.0.1:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: blog

logging:
  level:
    root: INFO
    org.lxly.blog: DEBUG

blog:
  jwt:
    # This must be a long secure random string (Base64 encoded preferred or just a long string)
    # Example: A 256-bit key
    secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
    # Token expiration time in milliseconds (e.g., 24 hours = 86400000)
    expiration: 86400000